config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'posts#index'

    devise_for :users
    resources :posts do
      resources :comments, only: %i[edit create update destroy], module: :posts
      resources :likes, only: %i[create destroy]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, uniqueness: true

  has_many :posts, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User', inverse_of: :posts
  belongs_to :category
  has_many :comments, dependent: :destroy, class_name: 'PostComment'
  has_many :likes, dependent: :destroy, class_name: 'PostLike'

  validates :title, presence: true, length: { minimum: 3, maximum: 256 }
  validates :body, presence: true
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_ancestry

  validates :content, presence: true, length: { minimum: 3 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'creator_id', dependent: :destroy, inverse_of: :creator
  has_many :likes, dependent: :destroy, class_name: 'PostLike'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  around_action :switch_locale

  private

  def switch_locale(&)
    locale = I18n.available_locales.include?(params[:locale]) ? params[:locale] : I18n.default_locale

    I18n.with_locale(locale, &)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_like, only: %i[destroy]
  before_action :set_post, only: %i[create destroy]
  before_action :redirect_if_guest, only: %i[create destroy]
  before_action :redirect_if_not_authorized, only: %i[destroy]

  def create
    like = PostLike.new
    like.user = current_user
    like.post = @post

    if like.save
      redirect_to @post
    else
      redirect_to @post, status: :unprocessable_entity
    end
  end

  def destroy
    if @like.destroy
      redirect_to @post
    else
      redirect_to @post, status: :unprocessable_entity
    end
  end

  private

  def redirect_if_guest
    redirect_to new_user_session_url unless user_signed_in?
  end

  def set_post
    @post = Post.find params[:post_id]
  end

  def set_like
    @like = PostLike.find params[:id]
  end

  def redirect_if_not_authorized
    redirect_to new_user_session_url unless user_is_like_creator?
  end

  def user_is_like_creator?
    @like.user.id == current_user.id
  end
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

class Posts::ApplicationController < ApplicationController
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < Posts::ApplicationController
  before_action :set_comment, only: %i[edit update destroy]
  before_action :redirect_if_guest, only: %i[create edit update destroy]
  before_action :redirect_if_not_authorized, only: %i[edit update destroy]

  def edit; end

  def create
    @post = Post.find(params[:post_id])
    comment = @post.comments.build(comment_params)
    parent_id = comment_params[:parent_id]
    comment.parent = PostComment.find(parent_id) if parent_id

    comment.user = current_user

    if comment.save
      redirect_to @post, notice: t('notice.comments.created')
    else
      flash[:failure] = comment.errors.first.full_message
      redirect_to @post
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment.post, notice: t('notice.comments.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = @comment.post
    @comment.destroy!

    redirect_to post, status: :see_other, notice: t('notice.comments.deleted')
  end

  private

  def set_comment
    @comment = PostComment.find(params[:id])
  end

  def comment_params
    params.require(:post_comment).permit(:user_id, :post_id, :content, :parent_id)
  end

  def redirect_if_guest
    redirect_to new_user_session_url unless user_signed_in?
  end

  def redirect_if_not_authorized
    render :show, status: :unauthorized unless user_is_comment_author?
  end

  def user_is_comment_author?
    @comment.user.id == current_user.id
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :redirect_if_guest, only: %i[create edit update destroy]
  before_action :redirect_if_not_authorized, only: %i[edit update destroy]

  def index
    @posts = Post.all
  end

  def show
    @can_edit = user_is_post_creator?
    @can_delete = user_is_post_creator?
    @comment = PostComment.new
    @comments = @post.comments.select { |comment| comment.parent.nil? }
    @likes_count = @post.likes.count
    @like = @post.likes.find_by(user_id: current_user.id) if user_signed_in?
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      redirect_to @post, notice: t('notice.posts.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: t('notice.posts.created')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!

    redirect_to posts_path, status: :see_other, notice: t('notice.posts.created')
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

  def redirect_if_guest
    redirect_to new_user_session_url unless user_signed_in?
  end

  def redirect_if_not_authorized
    render :show, status: :unauthorized unless user_is_post_creator?
  end

  def user_is_post_creator?
    user_signed_in? && @post.creator.id == current_user.id
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title
      = content_for(:title) || 'Rails Project 64'
    meta[name='viewport' content='width=device-width,initial-scale=1']
    meta[name='apple-mobile-web-app-capable' content='yes']
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link[rel='manifest' href='/manifest.json']
    link[rel='icon' href='/icon.png' type='image/png']
    link[rel='icon' href='/icon.svg' type='image/svg+xml']
    link[rel='apple-touch-icon' href='/icon.png']
    link[rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css']
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body.d-flex.flex-column.h-100
    header.container
      = render 'layouts/shared/nav'
    main.flex-shrink-0.mt-5.pt-3
      .container
        = render 'layouts/shared/flash'
      .container.pb-5
        = yield
    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- flash.any?
  - mapping = { 'failure' => 'danger', 'success' => 'success' }
  - flash.each do |name, msg|
    .alert.alert-dismissible.fade.show class="alert-#{mapping[name] || 'success'}"
      == msg
      button.btn-close type='button' data-bs-dismiss='alert'

app/views/layouts/shared/_footer.html.slim
footer.footer.mt-auto.py-3.bg-light
  .container
    span.text-muted Footer

app/views/layouts/shared/_nav.html.slim
.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
  .container-fluid
    = link_to t('home'), root_path, class: 'navbar-brand'
    button.navbar-toggler[type='button'
      data-bs-toggle='collapse'
      data-bs-target='#navbarNavAltMarkup'
      aria-controls='navbarNavAltMarkup'
      aria-expanded='false']
      span.navbar-toggler-icon
    .collapse.navbar-collapse[id='navbarNavAltMarkup']
      .navbar-nav.ms-auto.mb-2.mb-md-0
      - if user_signed_in?
        .nav-item
          = link_to t('create_new_post'), new_post_path, class: 'btn btn-primary me-2'
          = link_to t('sign_out'), destroy_user_session_path,
              data: { turbo_method: :delete }, class: 'btn btn-outline-success'
      - else
        .nav-item
          = link_to t('sign_in'), new_user_session_path, class: 'btn btn-outline-success me-2'
        .nav-item
          = link_to t('sign_up'), new_user_registration_path, class: 'btn btn-outline-success'

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  .form-inputs
    = f.input :title
    = f.input :body
    = f.association :category, selected: true

  .form-actions
    = f.submit class: 'btn btn-primary', value: t('submit')

app/views/posts/comments/_form.html.slim
= simple_form_for(comment, url:, html: { class: 'mb-3' }) do |f|
  .form-inputs
    - unless comment.parent.nil?
      = f.input :parent_id, as: :hidden, value: comment.parent.id
    = f.input :content, label: t('new_comment')

  .form-actions
    = f.submit class: 'btn btn-primary', value: t('submit')

app/views/posts/comments/_show.html.slim
.card.mb-2
  .card-header.d-flex.justify-content-between
    span = comment.user.email
    span = comment.created_at.strftime('%-d %b %Y %T')
  .card-body
    .card-text.mb-2 = comment.content
    a data-bs-target="#comment-#{comment.id}" class='btn btn-primary mb-3' data-bs-toggle= 'collapse' aria-controls="comment-#{comment.id}"
      = t('reply')
    .collapse id="comment-#{comment.id}"
      = render partial: 'posts/comments/form', locals: { comment: PostComment.build(parent: comment), url: post_comments_path(post_id:) }

    - comment.children.each do |child_comment|
      = render partial: 'posts/comments/show', locals: { comment: child_comment, post_id: child_comment.post_id }

app/views/posts/edit.html.slim
h1 Editing post

== render 'form', post: @post

.d-flex.gap-2.mt-3
  = link_to t('show_post'), @post, class: 'btn btn-outline-primary'
  = link_to t('back_to_posts'), posts_path, class: 'btn btn-outline-primary'
  = link_to t('destroy_post'), @post, method: :delete, class: 'btn btn-outline-danger ms-auto'

app/views/posts/index.html.slim
p style='color: green' = notice

h1 Posts

- @posts.each do |post|
  .card.mb-3
    .card-header.text-start
      = "#{post.creator.email} #{t('wrote')} at #{post[:created_at].strftime('%T %-d %b %Y')}:"
    .card-body
      h2.card-title = link_to post.title, post
      .card-subtitle.small = "#{t('category')}: #{post.category.name}"
      .card-text
        = truncate post.body, separator: /( |\.)/, length: 100
    .card-footer.d-flex
      .d-flex.ms-auto
        span.me-2 = t('liked')
        span = post.likes.count

app/views/posts/new.html.slim
h1 New post

== render 'form', post: @post

br

div
  = link_to 'Back to posts', posts_path

app/views/posts/show.html.slim
h1 = @post.title
p.small = "#{t('category')}: #{@post.category.name}"

p = simple_format @post.body

.d-flex.justify-content-between.mb-3
  time[pubdate] = @post.created_at.strftime('%T %-d %b %Y')
  .d-flex
    address.mb-0 = @post.creator.email
    .ms-3.d-flex.align-items-center
      .me-1 = @likes_count
      - if @like
        = link_to post_like_path(@post.id, @like.id), data: { turbo_method: :delete } do
          i.bi.bi-hand-thumbs-up-fill
      - else
        = link_to post_likes_path(@post.id), data: { turbo_method: :post } do
          i.bi.bi-hand-thumbs-up

.d-flex.gap-2.mb-2
  - if @can_edit
    = link_to t('edit_post'), edit_post_path(@post), class: 'btn btn-outline-primary'
  = link_to t('back_to_posts'), posts_path, class: 'btn btn-outline-primary'
  - if @can_delete
    = link_to t('destroy_post'), @post, method: :delete, class: 'btn btn-outline-danger ms-auto'

h2 = t('comments')
= render partial: 'posts/comments/form', locals: { comment: @comment, url: post_comments_path(@post) }
- @comments.each do |comment|
  = render partial: 'posts/comments/show', locals: { comment:, post_id: @post.id }